project:
  type: website
  output-dir: _preview
  execute-dir: project

resources:
  - _meta/assets

website:
  title: "Technical Library (Preview)"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  search: true
  navbar:
    background: "#a0b128"
    foreground: "#ffffff"
    search: false
  page-footer:
    left: |
      © 2025 EEA. All rights reserved.

format:
  html:
    output-dir: _preview # Moves rendered files outside src/
    include-before-body: includes/main-logos.html
    css: theme/main.css
